defmodule Defdo.MyApp.MyMvno.Resource.Package do
  use Ash.Resource,
    authorizers: [Ash.Policy.Authorizer],
    data_layer: AshPostgres.DataLayer,
    domain: Defdo.MyApp.Domain.MyMvno,
    extensions: [AshJsonApi.Resource]

  alias Defdo.MyApp.MyMvno.Actor

  postgres do
    table "mvno_packages"
    # With the same repo works.
    # repo MyApp.Repo
    # using another repo, cause the error
    repo Defdo.External.Repo
  end

  json_api do
    type "mvno_package"
  end

  policies do
    policy action_type(:read) do
      authorize_if relates_to_actor_via(:owner)
    end
  end

  actions do
    # Use the default implementation of the :read action
    defaults [:read, :create]
    default_accept :*
  end

  # Attributes are the simple pieces of data that exist on your resource
  attributes do
    # Add an autogenerated primary key called `:id`.
    integer_primary_key :id

    attribute :name, :string, public?: true
    attribute :mvno_id, :integer, public?: true

    create_timestamp :inserted_at, public?: true
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :owner, Actor do
      primary_key? false
      define_attribute? false

      attribute_type :string
      destination_attribute :mvno_profile_id
      source_attribute :mvno_id
    end
  end
end
