defmodule MyApp.Repo.Migrations.Bases do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenant_profiles, primary_key: false) do
      add :tenant_id,
          references(:tenant_profiles,
            column: :tenant_id,
            name: "tenant_profiles_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          default: fragment("gen_random_uuid()"),
          primary_key: true,
          null: false

      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:defdo_themes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenant_profiles,
            column: :tenant_id,
            name: "actor_apis_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:actor_apis, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :name, :text
      add :auth_method, :text, null: false
      add :code, :text
      add :mvno_profile_id, :bigint
      add :app_type, :text, null: false
      add :allowed_domains, {:array, :text}
      add :client_id, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenant_profiles,
            column: :tenant_id,
            name: "actor_apis_tenant_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:actor_apis, [:tenant_id, :code, :app_type, :client_id, :tenant_id],
             name: "actor_apis_unique_actor_index"
           )
  end

  def down do
    drop constraint(:defdo_themes, "defdo_themes_code_fkey")

    drop constraint(:defdo_themes, "defdo_themes_tenant_id_fkey")

    alter table(:defdo_themes) do
      modify :tenant_id, :uuid
      modify :code, :text
    end

    drop_if_exists unique_index(
                     :actor_apis,
                     [:tenant_id, :code, :app_type, :client_id, :tenant_id],
                     name: "actor_apis_unique_actor_index"
                   )

    drop constraint(:actor_apis, "actor_apis_tenant_id_fkey")

    drop table(:actor_apis)

    drop table(:defdo_themes)

    drop constraint(:tenant_profiles, "tenant_profiles_tenant_id_fkey")

    drop table(:tenant_profiles)
  end
end
